---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.17.1

jobs:
  include:
    - stage: 'Tests'
      name: 'Tests'
      script: bundle exec rspec
    - stage: 'Code style'
      name: 'Rubocop'
      script: bundle exec rubocop
